version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: mommyshops-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # Uncomment the following lines to automatically pull models on startup
    # command: >
    #   sh -c "ollama serve & 
    #          sleep 10 && 
    #          ollama pull llama3.1 && 
    #          ollama pull llava && 
    #          wait"

volumes:
  ollama_data:
    driver: local