apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: llama-31-8b-instruct
  namespace: nim-service
spec:
  image:
    repository: nvcr.io/nim/meta/llama-3.1-8b-instruct
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    pvc:
      create: true
      size: "20Gi"
      volumeAccessMode: "ReadWriteOnce"
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
  expose:
    service:
      type: ClusterIP
      port: 8000