# MommyShops - Configuración de Producción
# Configuración específica para producción

spring:
  # Database Configuration for Production
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mommyshops}
    username: ${DB_USERNAME:mommyshops}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  
  # Redis Configuration for Production
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
  
  # Security Configuration for Production
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}

# Python Backend Configuration for Production
python:
  backend:
    url: ${PYTHON_BACKEND_URL:http://localhost:8000}
    timeout: 30000

# External API Configuration for Production
external:
  api:
    fda:
      key: ${FDA_API_KEY:}
    ewg:
      key: ${EWG_API_KEY:}

# Ollama Configuration for Production
ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  model: ${OLLAMA_MODEL:llama3.1}
  vision-model: ${OLLAMA_VISION_MODEL:llava}

# Analysis Configuration for Production
analysis:
  confidence:
    threshold: 80
  max-ingredients: 50

# Monitoring Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration for Production
logging:
  level:
    com.mommyshops: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/mommyshops/mommyshops.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

