# MommyShops - Configuración de Desarrollo
# Configuración específica para desarrollo local

spring:
  # Database Configuration for Development
  datasource:
    url: jdbc:postgresql://localhost:5432/mommyshops_dev
    username: mommyshops_dev
    password: dev_password
  
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # Redis Configuration for Development
  data:
    redis:
      host: localhost
      port: 6379
  
  # Security Configuration for Development
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}

# Python Backend Configuration for Development
python:
  backend:
    url: http://localhost:8000
    timeout: 30000

# External API Configuration for Development
external:
  api:
    fda:
      key: ${FDA_API_KEY:}
    ewg:
      key: ${EWG_API_KEY:}

# Ollama Configuration for Development
ollama:
  base-url: http://localhost:11434
  model: llama3.1
  vision-model: llava

# Analysis Configuration for Development
analysis:
  confidence:
    threshold: 60
  max-ingredients: 30

# Logging Configuration for Development
logging:
  level:
    com.mommyshops: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

