server:
  port: 8080

spring:
  application:
    name: mommyshops-backend
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/mommyshops
    username: mommyshops
    password: change-me
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Backend configuration
ollama:
  base-url: http://localhost:11434
  model: llama3.1
  vision-model: llava

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always